name: jdihkotakendari
description: "Aplikasi Mobile JDIH Kota Kendari"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  flutter_cached_pdfview: ^0.4.3
  url_launcher: ^6.2.4
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linter untuk menjaga kerapihan kode
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # Bagian assets (gambar) nanti kita isi di sini kalau sudah ada logo
  # assets:
  #   - assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21