name: jdihkotakendari
description: "Aplikasi Mobile JDIH Kota Kendari"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  path_provider: ^2.1.2  # Untuk cari folder temp di HP
  
  open_filex: ^4.3.2     # Untuk buka file PDF yang sudah didownload

  flutter:
    sdk: flutter

  # Icon bawaan iOS
  cupertino_icons: ^1.0.8

  # --- TAMBAHAN KITA ---
  
  # Untuk koneksi ke API Laravel
  http: ^1.2.0
  
  # Untuk font yang bagus (Lato/Roboto)
  google_fonts: ^6.1.0
  
  # Untuk format tanggal (contoh: 28 Januari 2026)
  intl: ^0.19.0
  
  # Untuk membuka link PDF di browser/aplikasi luar
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linter untuk menjaga kerapihan kode
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Bagian assets (gambar) nanti kita isi di sini kalau sudah ada logo
  # assets:
  #   - assets/images/logo.png